### ISSUE TITLE
Multiple pickle failures in the pathos examples and tests

### ISSUE THREAD

**Issue by Zebrafish007** [uqfoundation/pathos#125] opened 2017-11-09 15:42 UTC
Dear Mr. Mike McKerns,

I've encountered a lot of titties & beer errors in various provided scripts with the pathos example and test folder. They might be related to each other. Not sure. See attachment for tracebacks on each file I had a bump with. I hope you can help me out here... 7 cores are waiting to be fed with ... pickles.

Most reoccurring song theme (a.k.a. error messages) in the attached bug-file: 

* cPickle.PicklingError:  Can't pickle <type 'function'>: attribute lookup __builtin__.function failed"

> Ill give you two clues. Let go of your Pickle
* What?
> Let go of your cPickle!
* I'm not holding my cPickle.PicklingError
> Well, whos holding your pickle error then?       --> **(attached bug file**),..
* I don't know... She "dills" out in the audience...  --> python, conda or sir pickle-lot... i guess

(... Frank Zappa)

--- some sys and install info ---
> via pip : pathos 0.2.1 & multiprocess (0.70.5), 
>via conda: dill 0.2.7.1.
> Anaconda2; python 2.7.13, windows 10. komodo edit 10.2.3 and 11.0.

These pickle errors also work on the StackOverflow example when the defs are placed in a class:

https://stackoverflow.com/questions/20887555/dead-simple-example-of-using-multiprocessing-queue-pool-and-locking

...and your answer: https://stackoverflow.com/a/21345273
 
[pathos errors (dir_examples_and_dir_test).txt](https://github.com/uqfoundation/pathos/files/1458088/pathos.errors.dir_examples_and_dir_test.txt)

------------------
snippet scriptcode
------------------
    class Multiprocess(object):
    
    def __init__(self):
        pass
    
    def qmp_worker(self,(inputs, the_time)):
        print " Processs %s\tWaiting %s seconds" % (inputs, the_time)
        time.sleep(int(the_time))
        print " Process %s\tDONE" % inputs
    
    def qmp_handler(self):                           # Non tandem pair processing
        pool = pp.ProcessPool(2)
        pool.map(self.qmp_worker, data)
    

    def mp_worker((inputs, the_time)):
        print " Processs %s\tWaiting %s seconds" % (inputs, the_time)
        time.sleep(int(the_time))
        print " Process %s\tDONE" % inputs

    def mp_handler():                           # Non tandem pair processing
        p = multiprocessing.Pool(2)
        p.map(mp_worker, data)
    
    def mp_handler_tandem():
        subdata = zip(data[0::2], data[1::2])
        print subdata
        for task1, task2 in subdata:
            p = multiprocessing.Pool(2)
            p.map(mp_worker, (task1, task2))

    #data = (['a', '1'], ['b', '2'], ['c', '3'], ['d', '4'])
    data = (['a', '2'], ['b', '3'], ['c', '1'], ['d', '4'], ['e', '1'], ['f', '2'], ['g', '3'], ['h', '4'])
    
    if __name__ == '__main__':
        mp_handler()
        mp_handler_tandem()
    
        Multiprocess().qmp_handler()

**Comment by Zebrafish007** [comment] 2017-11-12 10:34
I've stumbled upon something that might be an answer to the pickle issue here at had.. not sure though.

In the case of PyQt5 not reporting back errors as we used to see for "traceback" result in standard out there is an implementation to catch this given bu Vanloc on StackOverflow. The link:

https://stackoverflow.com/a/43039363

Here Vanloc implements:

To catch the exceptions, you need to overwrite the sys exception handler:

```
# Back up the reference to the exceptionhook
sys._excepthook = sys.excepthook

def my_exception_hook(exctype, value, traceback):
    # Print the error and traceback
    print(exctype, value, traceback)
    # Call the normal Exception hook after
    sys._excepthook(exctype, value, traceback)
    sys.exit(1)

# Set the exception hook to our wrapping function
sys.excepthook = my_exception_hook
```

Then in your execution code, wrap it in a try/catch.

```
try:
    sys.exit(app.exec_())
except:
    print("Exiting")
```

So the question is... should something similar be done with pickle and dill like below code given by vanloc in response to the issue T4ng10r had with his Nvidea driver and PyQt5 not reporting back in a pythonic way?

```
    # Back up the reference to the exceptionhook
    sys._excepthook = sys.excepthook

    # Set the exception hook to our wrapping function
    sys.excepthook = my_exception_hook
```

**Comment by Zebrafish007** [comment] 2017-11-29 06:38
On windwos 10 your mp_example.py script code produces the below error:

    import dill
    import pickle
    import multiprocessing
    from pathos.pools import ProcessPool, ThreadPool
    import pathos.helpers
    from multiprocessing import freeze_support
    import logging
    log = logging.getLogger(__name__)
    
    class PMPExample(object):
        def __init__(self):
            self.cache = {}
    
        def compute(self, x):
            self.cache[x] = x ** 3
            return self.cache[x]
    
        def threadcompute(self, xs):
            pool = ThreadPool(4)
            results = pool.map(self.compute, xs)
            return results
    
        def processcompute(self, xs):
            pool = ProcessPool(4)
            results = pool.map(self.compute, xs)
            return results
    
    def parcompute_example():
        dc = PMPExample()
        dc2 = PMPExample()
        dc3 = PMPExample()
        dc4 = PMPExample()

        n_datapoints = 100
        inp_data = range(n_datapoints)
        r1 = dc.threadcompute(inp_data)
        assert(len(dc.cache) == n_datapoints)

        r2 = dc2.processcompute(inp_data)
        assert(len(dc2.cache) == 0)
        assert(r1 == r2)
    
        r3 = ProcessPool(4).map(dc3.compute, inp_data)
        r4 = ThreadPool(4).map(dc4.compute, inp_data)
        assert(r4 == r3 == r2)
        assert(len(dc3.cache) == 0)
        assert(len(dc4.cache) == n_datapoints)
    
        log.info("Size of threadpooled class caches: {0}, {1}".format(len(dc.cache), len(dc4.cache)))
        log.info("Size of processpooled class caches: {0}, {1}".format(len(dc2.cache), len(dc3.cache)))
    
    if __name__ == '__main__':
        pathos.helpers.freeze_support()
        logging.basicConfig()
        log.setLevel(logging.INFO)

        parcompute_example()`

The error:

> Traceback (most recent call last):
  File "D:\Scripts\Thirdparty\Pathos\mp_class_example.py", line 64, in <module>
    parcompute_example()
  File "D:\Scripts\Thirdparty\Pathos\mp_class_example.py", line 46, in parcompute_example
    r2 = dc2.processcompute(inp_data)
  File "D:\Scripts\Thirdparty\Pathos\mp_class_example.py", line 32, in processcompute
    results = pool.map(self.compute, xs)
  File "c:\python\anac2\lib\site-packages\pathos\multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "c:\python\anac2\lib\site-packages\multiprocess\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "c:\python\anac2\lib\site-packages\multiprocess\pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

**Comment by mmckerns** [comment] 2017-12-03 01:03
I have tried your script on Windows 10, using the most recent version (from GitHub) of `dill` and `pathos`, using python 2.7.10.  It's not the exact same as your versions, but I don't see any errors with my configuration.  I'll need to do a little more work to match your versions... but maybe you can try with the most recent versions of the code and see if the error you see still persists?

Another thing we can try is to simplify the example (or examples), and then run with `dill.detect.trace(True)`.  Then compare the trace to see where mine succeeds and yours fails.

**Comment by Zebrafish007** [comment] 2017-12-06 12:53
I'll try the dill detect tonight and provide you with feedback thereafter.

**Comment by Waponiwoo** [comment] 2018-02-12 23:28
getting same error in a conda environment using spyder.  i can't get this insert code to work correctly, but here is the code:
`
import dill
dill.detect.trace(True)

def host(x):
    return x*x

if __name__ == '__main__':
    from pathos.helpers import freeze_support
    freeze_support()

    from pathos.pools import ProcessPool as Pool
    pool = Pool()

    pool.ncpus = 2
    res3 = pool.map(host, range(5))
    print(pool)
    print('\n'.join(res3))
    print('')
`

**output:**

`
import dill
dill.detect.trace(True)

def host(x):
    return x*x


if __name__ == '__main__':
    from pathos.helpers import freeze_support
    freeze_support()
    
    from pathos.pools import ProcessPool as Pool
    pool = Pool()
    
    pool.ncpus = 2
    res3 = pool.map(host, range(5))
    print(pool)
    print('\n'.join(res3))
    print('')
D2: <dict object at 0x0000000007F3A8C8>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F3A598>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F3A6A8>
# D2
# D2
D2: <dict object at 0x0000000007F49158>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F3AAE8>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F49048>
# D2
# D2
D2: <dict object at 0x0000000007F4BAE8>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F42BF8>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F4B9D8>
# D2
# D2
D2: <dict object at 0x0000000007F50598>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F42D08>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F50488>
# D2
# D2
D2: <dict object at 0x0000000007F51158>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F3A7B8>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F51048>
# D2
# D2
D2: <dict object at 0x0000000007F537B8>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F3FAE8>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F536A8>
# D2
# D2
D2: <dict object at 0x0000000007F539D8>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F4D7B8>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F538C8>
# D2
# D2
D2: <dict object at 0x0000000007F53BF8>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F3FD08>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F53AE8>
# D2
# D2
D2: <dict object at 0x0000000007F53E18>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F51D08>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F53D08>
# D2
# D2
D2: <dict object at 0x0000000007F56158>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F51AE8>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F56048>
# D2
# D2
D2: <dict object at 0x0000000007F56378>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F50BF8>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F56268>
# D2
# D2
D2: <dict object at 0x0000000007F56598>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F4D048>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F56488>
# D2
# D2
D2: <dict object at 0x0000000007F567B8>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F4B158>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F566A8>
# D2
# D2
D2: <dict object at 0x0000000007F57158>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F4B268>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F57048>
# D2
# D2
D2: <dict object at 0x0000000007F57378>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F496A8>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F57268>
# D2
# D2
D2: <dict object at 0x0000000007F57598>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F51488>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F57488>
# D2
# D2
D2: <dict object at 0x0000000007F466A8>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F50158>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F449D8>
# D2
# D2
D2: <dict object at 0x0000000007F46048>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.process.Process'>
# T4
D2: <dict object at 0x0000000007F4B488>
F2: <function worker at 0x0000000007E2C518>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
T4: <type '_multiprocessing.PipeConnection'>
# T4
T4: <class 'multiprocess.synchronize.Lock'>
# T4
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
D2: <dict object at 0x0000000007F467B8>
# D2
# D2
Traceback (most recent call last):

  File "<ipython-input-1-5c15322e47d7>", line 16, in <module>
    res3 = pool.map(host, range(5))

  File "D:\Anaconda2\envs\Everything_1_22_18\lib\site-packages\pathos\multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize

  File "D:\Anaconda2\envs\Everything_1_22_18\lib\site-packages\multiprocess\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()

  File "D:\Anaconda2\envs\Everything_1_22_18\lib\site-packages\multiprocess\pool.py", line 567, in get
    raise self._value

PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
`

**Comment by mmckerns** [comment] 2018-03-17 20:20
@Waponiwoo: Are you using python `2.7`... and if so, can you confirm that you have a C compiler?  Because if you don't have a C compiler, then `multiprocess` may not have built correctly and you might see the error you have posted.   I run your example code, and it works for me.

@Zebrafish007: **Are you still having issues, or can this be closed?**  I don't get your error either, and it may be due to the same reason... that you are missing a C compiler.  I also tried your initial snippet and the code wasn't valid... so I edited it and now it works.  I also didn't have a problem with it running once edited:
```
from pathos import multiprocessing, pools as pp
import time


class Multiprocess(object):

    def __init__(self):
        pass

    def qmp_worker(self,(inputs, the_time)):
        print " Processs %s\tWaiting %s seconds" % (inputs, the_time)
        time.sleep(int(the_time))
        print " Process %s\tDONE" % inputs

    def qmp_handler(self):                      # Non tandem pair processing
        pool = pp.ProcessPool(2)
        pool.map(self.qmp_worker, data)


def mp_worker((inputs, the_time)):
    print " Processs %s\tWaiting %s seconds" % (inputs, the_time)
    time.sleep(int(the_time))
    print " Process %s\tDONE" % inputs

def mp_handler():                           # Non tandem pair processing
    p = multiprocessing.Pool(2)
    p.map(mp_worker, data)

def mp_handler_tandem():
    subdata = zip(data[0::2], data[1::2])
    print subdata
    for task1, task2 in subdata:
        p = multiprocessing.Pool(2)
        p.map(mp_worker, (task1, task2))


#data = (['a', '1'], ['b', '2'], ['c', '3'], ['d', '4'])
data = (['a', '2'], ['b', '3'], ['c', '1'], ['d', '4'], ['e', '1'], ['f', '2'], ['g', '3'], ['h', '4'])

if __name__ == '__main__':
    mp_handler()
    mp_handler_tandem()

    Multiprocess().qmp_handler()
```

**Comment by mmckerns** [comment] 2018-03-26 04:35
Since I can't reproduce the errors, and both reporters tracebacks have the signature of missing a `C` compiler, I'm going to close this issue.  If either of you do have a `C` compiler, and are still experiencing issues, then please reopen the ticket.

**Closed by mmckerns** 2018-03-26 04:35 UTC
Labels: voided

**Comment by gziras-in** [comment] 2022-01-11 09:14
#227 It seems that there exists the same issue.
