### ISSUE TITLE
install fails for python 3.x

### ISSUE THREAD

**Issue by wsw70** [uqfoundation/pathos#68] opened 2015-07-24 12:40 UTC
Installing the latest pathos on Windows 8.1 64 fails:

```
C:\Windows\System32>c:\Python34\Scripts\pip.exe install git+https://github.com/uqfoundation/pathos.git@master
Collecting git+https://github.com/uqfoundation/pathos.git@master
  Cloning https://github.com/uqfoundation/pathos.git (to master) to c:\users\yop\appdata\local\temp\pip-2mnr27u9-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\yop\AppData\Local\Temp\pip-2mnr27u9-build\setup.py", line 363
        exec setup_code
                      ^
    SyntaxError: Missing parentheses in call to 'exec'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\yop\AppData\Local\Temp\pip-2mnr27u9-build
```

**Comment by mmckerns** [comment] 2015-07-24 12:43
Which version of python?

`pathos` is 90% python 3.x compatible, but I have not completed the conversion to python 3.x yet.

**Comment by wsw70** [comment] 2015-07-24 12:44
Sorry, forgot about that - this is python 3.4

**Comment by mmckerns** [comment] 2015-07-24 12:47
I just noticed that from your traceback.  I expect that `pathos` will be 3.x compatible in less than a month, depending on opportunity I get.  It's almost converted.  No worries.  Your ticket is a good reminder to get it done.

**Comment by mmckerns** [comment] 2015-07-24 12:49
Duplicate of #1.

**Closed by mmckerns** 2015-07-24 12:49 UTC
Labels: duplicate

**Comment by vmsv** [comment] 2016-01-20 09:32
Also fails on Windows 7 64-bit python 3.5.1-32bit

**Comment by mmckerns** [comment] 2016-01-20 11:17
@vmsv: I haven't finished the conversion as I'd expected, so yes, there's still 10% of it that's not 3.x compatible.  However, you can get 75% of the functionality of `pathos` from submodules `multiprocess` and `ppft`, which are python 3.x compatible. These submodules install with `pip` (and note that `multiprocess` requires a C compiler).
