### ISSUE TITLE
io.UnsupportedOperation: seek

### ISSUE THREAD

**Issue by Prabhaaharan** [uqfoundation/pathos#155] opened 2018-10-11 01:27 UTC
I am trying download all the images given in the dataset. 

> kaggle datasets download -d crowdflower/twitter-user-gender-classification

I ran this script

[image_extraction.zip](https://github.com/uqfoundation/pathos/files/2467025/image_extraction.zip)

But I got issues after running for 150 dataset which is part of 20k dataset.

_Traceback (most recent call last):
  File "E:/image_extraction.py", line 29, in <module>
    get_images(imgURL[i],uniID[i],gender[i],i)
  File "E:/image_extraction.py", line 20, in get_images
    k=imageio.imread(image_url)
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\core\functions.py", line 221, in imread
    reader = read(uri, format, "i", **kwargs)
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\core\functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\core\format.py", line 174, in get_reader
    return self.Reader(self, request)
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\core\format.py", line 224, in __init__
    self._open(**self.request.kwargs.copy())
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\plugins\pillowmulti.py", line 57, in _open
    return PillowFormat.Reader._open(self)
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\plugins\pillow.py", line 132, in _open
    if hasattr(self._im, "n_frames"):
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\GifImagePlugin.py", line 96, in n_frames
    self.seek(self.tell() + 1)
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\GifImagePlugin.py", line 128, in seek
    self._seek(f)
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\GifImagePlugin.py", line 158, in _seek
    self.fp.seek(self.__offset)
  File "C:\Users\prabhu\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\core\request.py", line 513, in seek
    ori_seek(i, mode)
io.UnsupportedOperation: seek_

Need Help to resolve this.

**Comment by mmckerns** [comment] 2018-12-23 16:46
@Prabhaaharan: I don't see this being a `pathos` issue...  I'm closing this issue, but feel free to reopen it if you have more information... (e.g. you can produce a minimal self-contained bit of code that demonstrates the error you are seeing, and it demonstrates that `pathos` is the cause).

**Closed by mmckerns** 2018-12-23 16:46 UTC
Labels: voided
