### ISSUE TITLE
How to stop memory leakage?

### ISSUE THREAD

**Issue by RJTK** [uqfoundation/pathos#131] opened 2018-02-05 15:32 UTC
I am confused about what seems to be a significant difference between the way Python's multiprocessing.Pool works and the way pathos.multiprocessing.ProcessPool works.

My program runs (serially) a loop which on every iterations calls a function that forks a bunch of Pathos ProcessPools, does some work, and then returns.  The memory usage of this program continually climbs and eventually eats up everything available.

If this were implemented with Python's multiprocessing.Pool, this can be fixed either by closing the pool at the end of each function call, or by creating the pool before the main serial loop and reusing the same one on each call.  However, neither of these solutions seem to work with Pathos.  The former fails with an error 'pool is not running', and the latter still continually bogs down available memory.

The following code illustrates the problem.

```
from pathos.multiprocessing import ProcessPool
from multiprocessing import Pool

NUM_LOOPS = 10000

def do_stuff(x):
    return

def use_pathos_pool(pool=None):
    if pool is None:
        pool = ProcessPool(3)
    pool.map(do_stuff, [1, 2, 3])

    # This fails with error 'pool not running'
    # pool.close()
    # pool.join()
    return

def use_python_pool(pool=None):
    if pool is None:
        pool = Pool(3)
    pool.map(do_stuff, [1, 2, 3])

    # This prevents test003 from exploding memory
    # pool.close()
    # pool.join()
    return

def test001():
    '''Memory usage slowly grows'''
    for _ in range(NUM_LOOPS):
        use_pathos_pool()
    return

def test002():
    '''Memory usage slowly grows'''
    pathos_pool = ProcessPool(3)
    for _ in range(NUM_LOOPS):
        use_pathos_pool(pathos_pool)
    return

def test003():
    '''Memory usage explodes'''
    for _ in range(NUM_LOOPS):
        use_python_pool()
    return

def test004():
    '''Memory usage stays constant'''
    python_pool = Pool(3)
    for _ in range(NUM_LOOPS):
        use_python_pool(python_pool)
    return
```

**Comment by ZhengRui** [comment] 2018-04-27 01:11
I am facing a similar issue, have you found any solution?

**Comment by mmckerns** [comment] 2018-06-14 23:11
`pathos` intentionally keeps the pool instance alive, so the typical `close` then `join` doesn't destroy the pool, it leaves a joined pool in memory.  This is intentional, because it's faster to restart from an existing pool than it is to create a new one.

If you want to reuse an pool after you have called `close`/`join`, then you can call `restart`.  If you want to delete the pool (i.e. clear it from memory), then call `clear`.

**Comment by mmckerns** [comment] 2018-06-14 23:14
See the example in #111.  What you are seeing is expected behavior... there's a mechanism to destroy old pools, and the default is to keep and potentially reuse them.

**Comment by ido-a** [comment] 2019-09-10 08:05
I believe there can still be a memory leak (or more accurately, a process leak) in the way ProcessPool allocates pools. Suppose you have a loop with two steps:
1. creating a ProcessPool object with 40 workers and use it (using a with statement)
2. creating a ProcessPool object with 20 workers and use it (using a with statement)
pathos will keep creating new pools without closing the previous ones.

The origin of the problem is that the \__init__ method updates its __nodes attribute, _serve than calls _clear which does nothing since self.__nodes == _pool.__nodes no longer holds. Thus the pool is not closed and a new one is created, leaving the old pool behind. When this is done repeatedly, things get out of hand.

**Comment by mmckerns** [comment] 2019-09-27 20:31
@ido-a: Hmm... that may be true. I'll investigate that.  Did you try calling `pool.clear()` or using `helper.shutdown`?  Both of those are intended to clear out old pool instances.

**Comment by 3fon3fonov** [comment] 2019-09-29 16:45
Dear all, 

I think I am in the right place and at the right time to report a similar problem.

I am running an expensive mcmc scheme via the emcee sampler. The function "run_mcmc"
is scripted in a large for loop. With each iteration I want to start a new fresh pool. However, I noticed that while the loop is running I an accumulating memory, to the point that an easy mcmc run that would usually take ~ 60 sec now takes an hour and more and it gets worse.  

How can I close the pathos pool? 
Please also note that the "CustomSampler" is a wrapper around emcee, which has it own "pool" argument, where ideally the pool object must be passed. 

```
def run_mcmc(obj,  prior=0, samplesfile='', level=(100.0-68.3)/2.0, threads=1, save_means=False, save_maxlnL=False, save_mode= False,  fileoutput=False, save_sampler=False,burning_ph=10, mcmc_ph=10, **kwargs):          
    
    '''Performs MCMC and saves results'''  
     # 
     #  many unimportant lines removed, therefore this is not a working example!
     #  full code available at: https://github.com/3fon3fonov/trifon  in lib/RV_mod/__init__.py
     #  relevant part of the code below.

    from pathos.pools import ProcessPool as Pool
    pool=Pool(ncpus=threads)
 
    ndim, nwalkers = len(pp), len(pp)*obj.nwalkers_fact
    pos = [pp + obj.gaussian_ball*np.random.rand(ndim) for i in range(nwalkers)]
 
    sampler = CustomSampler(nwalkers, ndim, lnprob_new, args=(mod, par, flags, npl, vel_files, tr_files,  tr_model, tr_params, epoch, stmass, bb, priors, gps, tra_gps, rtg, mix_fit,opt), pool=pool)
 
    # burning phase
    pos, prob, state  = sampler.run_mcmc(pos,burning_ph)
    sampler.reset()
    
    # now perform the MCMC
    pos, prob, state  = sampler.run_mcmc(pos,mcmc_ph)
  
    #ln = np.hstack(sampler.lnprobability)
    sampler.save_samples(obj.f_for_mcmc,obj.filelist.ndset,obj.npl)

    pool.close()
    pool.join() 
    pool.clear()   `


    # rest of the code...
```

**Comment by mmckerns** [comment] 2019-09-29 18:53
@3fon3fonov: `clear` should close a `pathos` pool.  However, it's possible that there are some issues depending on how the pool is built (re: @ido-a's message above).  I just added a new helper method (`pathos.helpers.shutdown`) which may resolve this issue.  Feel free to try it... it needs testing before I can say that it resolves this issue.

**Comment by 3fon3fonov** [comment] 2019-09-29 19:59
Dear mmckerns,

I am not sure I use it correctly but:

```
    import pathos as ps
    pool.close()
    pool.join()
#    pool.restart()
    pool.clear()
    ps.helpers.shutdown()
```

It does not work so far... I am quite puzzled... looking at 'top' (I am on Linux), with each loop iteration is pumping the memory usage to each of the pooled processes. For example, as I am writing this I am running simultaneously 20 processes each with 2 Gb of used RAM! However, looking at the "top" system memory says the overall usage is 35 Gb, which is approx. with what I started. But there must be a problem because the simulations really got slower and slower... 

Also, I never experienced this when I am running my GUI, at least I have not noticed. Many time I am running sequent mcmc runs on one object and It always execute for almost the same amount of time.

BTW, fyi, in the GUI I call the run_mcmc() routing with a Qt worker. Do you think this somewhat may eliminate the problem? And when I ran the run_mcmc in a script (looping, without closing the process) may cause problems? I am not sure what is going on, I hope you figure it out as I need my mcmc runs urgently :) 

in the GUI i do the following:

```
    def worker_mcmc(self):
        global fit  
        
        
        if self.radioButton_RV.isChecked():
            fit.rtg = [True,self.do_RV_GP.isChecked(), False, self.do_tra_GP.isChecked()]
        elif self.radioButton_transit.isChecked():
            fit.rtg = [False, self.do_RV_GP.isChecked(), True, self.do_tra_GP.isChecked()]
        elif self.radioButton_transit_RV.isChecked():
            fit.rtg = [True,self.do_RV_GP.isChecked(), True, self.do_tra_GP.isChecked()]
        
        self.button_MCMC.setEnabled(False)
        self.statusBar().showMessage('MCMC in progress....')        
        # check if RV data is present
        if fit.type_fit["RV"] == True and fit.filelist.ndset <= 0:
             choice = QtGui.QMessageBox.information(self, 'Warning!',
             "Not possible to run MCMC if there are no RV data loaded. Please add your RV data first. Okay?", QtGui.QMessageBox.Ok)      
             self.button_MCMC.setEnabled(True)  
             self.statusBar().showMessage('') 

             return   
        
        ntran_data = 0
        for i in range(0,10,1):         
            ntran_data += len(fit.tra_data_sets[i]) 
            
        if fit.type_fit["Transit"] == True  and ntran_data == 0:
             choice = QtGui.QMessageBox.information(self, 'Warning!',
             "Not possible to run MCMC if there are no transit data loaded. Please add your transit data first. Okay?", QtGui.QMessageBox.Ok)      
             self.button_MCMC.setEnabled(True)  
             self.statusBar().showMessage('') 

             return             
    

        choice = QtGui.QMessageBox.information(self, 'Warning!',
                                            "This will run in the background and may take some time. Results are printed in the 'Stdout/Stderr' tab. Okay?",
                                            QtGui.QMessageBox.Cancel | QtGui.QMessageBox.Ok)       
         
        if choice == QtGui.QMessageBox.Cancel:
            self.statusBar().showMessage('') 
            self.button_MCMC.setEnabled(True)
            return        

        self.set_tra_ld()        
        self.check_bounds()
        self.check_priors_nr() 
        fit.model_npoints = self.points_to_draw_model.value()
        
        self.tabWidget_helper.setCurrentWidget(self.tab_info)
        
        
        if self.use_percentile_level.isChecked():
            fit.percentile_level = self.percentile_level.value()
        else:
            fit.percentile_level = 68.3
           
        
        # Pass the function to execute
        worker = Worker(lambda: self.run_mcmc()) # Any other args, kwargs are passed to the run  
        # Execute
        worker.signals.finished.connect(self.worker_mcmc_complete)
        
        # worker.signals.result.connect(self.print_output)
        #worker.signals.finished.connect(self.thread_complete)
       # worker.signals.progress.connect(self.progress_fn)
        self.threadpool.start(worker)
        
    def run_mcmc(self):
        global fit
        
 
        self.check_model_params()
        self.check_mcmc_params()
      
        fit = rv.run_mcmc(fit, burning_ph=self.burning_phase.value(), mcmc_ph=self.mcmc_phase.value(), threads=int(self.N_threads.value()), output=False,
        fileoutput=self.save_samples.isChecked(),save_means=self.adopt_mcmc_means_as_par.isChecked(), save_mode=self.adopt_mcmc_mode_as_par.isChecked(),
        save_maxlnL=self.adopt_best_lnL_as_pars.isChecked(),save_sampler=True)

```

**Comment by mmckerns** [comment] 2019-09-30 00:50
`shutdown` is meant to remove the cached pools -- you call it when you are done with the pools.  It's intended to have the effect of deleting a closed/joined pool.

**Comment by 3fon3fonov** [comment] 2019-09-30 14:19
Hi again, 

as you can see from my first message, I am using:

```
    from pathos.pools import ProcessPool as Pool
    pool=Pool(ncpus=threads) 
```

I tried almost everything,    "  from pathos.multiprocessing import ProcessingPool as Pool"
"from pathos.pools import ProcessPool as Pool",  "from pathos.pools import ParallelPool as Pool",
"from multiprocessing import Pool", "from multiprocess import Pool", "from pathos.pools import ThreadPool as Pool"....

and I always get to the same problem when the code is executed in a loop, and no obvious problem 
when executed from the GUI, where run_mcmc() is pooled in a threadpool worker (see above).

I might be missing something, somewhere, but what I really need is to gain speed by running the pool in each processor, i.e. not doing threads. As far as I understand pathos.pools.ProcessPool is my weapon of choice. Apart from this problem, I see that none of my 20+ CPUs is actually running on 100 %, and it seems that the memory usage is shared. Would that be an indication of a problem? 

Is it possible that I get an error inside the loop, but since I cannot get the stderr/stdout when I run the pooled simulations I never properly close the pool? How can I get an indication if an error was raised? 

I really want to rely on phatos for my project, so I hope we find a solution for this memory leak. If you are interested to investigate further I can prepare a working example for you and send you the files in a PM.

**Comment by 3fon3fonov** [comment] 2019-10-01 08:32
Hi Again,

The memory problem was fixed, by a small hack.

I had to create a separate script that loads the .ses session,
runs the mcmc and saves it back. Then in the main loop it looks like this:

```
......
......

file_ses = open("./ses/%s.ses"%target_name, 'wb')
dill.dump(fit, file_ses)
file_ses.close()

os.system("python run_mcmc_from_ses.py -ses ./ses/%s.ses
%s"%(target_name,target_name))

file_ses = open("./ses/%s.ses"%target_name, 'rb')
fit = dill.load(file_ses)
file_ses.close()


......
......
```


it is ugly, but it works. 

So by running a separate process with the mcmc all processes use about 80 Mb at once without gaining memory usage. This tells us something about the pool usage in a loop started from one process....

I am still puzzled why my I never get 20 x 100 % CPU usage if I have the resources.
All processes run around ~15% at max. But for this I will read more and perhaps open a separate "issue".

**Comment by ido-a** [comment] 2019-10-02 05:19
> @ido-a: Hmm... that may be true. I'll investigate that. Did you try calling `pool.clear()` or using `helper.shutdown`? Both of those are intended to clear out old pool instances.

Thanks, I indeed used pool.clear() in an ad-hoc solution of the leak. The problem with it is that the number of workers in my code is determined at runtime based on the number of computational tasks. In many cases it remains the same and sometimes the overhead of unnecessarily creating a new pool each time is not insignificant if the tasks are relatively short.

**Comment by duducosmos** [comment] 2020-03-26 21:32
Thanks, I tried shutdown, but only pool.clear() solved my problem.

**Comment by mmckerns** [comment] 2023-02-01 04:53
I'm closing this.  Essentially, use `clear` to clear out the singleton `Pool` and stop the memory leak.  If you don't have a need for too many iterations over a pool, then you can skip the `clear` to save a little bit of time in creating new pools.

**Closed by mmckerns** 2023-02-01 04:53 UTC
Labels: question
