### ISSUE TITLE
When I use pathos and pymongo, maximum recursion depth exceeded .

### ISSUE THREAD

**Issue by maxbitcoin** [uqfoundation/pathos#85] opened 2016-06-11 04:55 UTC
Version:pymongo 3.2.2;python 2.7;mongodb 3.0.12；pathos 0.2a1.dev0
When I was using pathos for python multiprocessing，the following mistick happened. I comment this line:“self.db_userinfo_table = MongoClient('localhost',27017).collection.example”，It can run nornaly.But if I don't comment this line,the line:“result = ProcessPool(4).map(r.compute, range(100))”can't run.,the line:“result = ThreadPool(4).map(r.compute, range(100))”can't run well on matter if I comment mongodb client.

```
from pathos.pools import ProcessPool, ThreadPool
import logging
from pymongo import MongoClient

class PMPExample(object):
    def __init__(self):
        self.cache = {}
        self.db_userinfo_table  = MongoClient('localhost',27017).collection.example
    def compute(self, x):
        self.cache[x] = x ** 3
        return self.cache[x]

if __name__ == '__main__':
    logging.basicConfig()
    log = logging.getLogger(__name__)
    log.setLevel(logging.INFO)
    r = PMPExample()
    #result = ThreadPool(4).map(r.compute, range(100))
    result = ProcessPool(4).map(r.compute, range(100))
    log.info("result processpooled caches: {}".format(result))
```

This is the event log:

  File "C:\Python27\lib\site-packages\pymongo\collection.py", line 228, in **getattr**
    full_name = _UJOIN % (self.__name, name)
  File "C:\Python27\lib\site-packages\pymongo\collection.py", line 228, in __getattr__
    full_name = _UJOIN % (self.__name, name)
  File "C:\Python27\lib\site-packages\pymongo\collection.py", line 228, in __getattr__
    full_name = _UJOIN % (self.__name, name)
  File "C:\Python27\lib\site-packages\pymongo\collection.py", line 228, in __getattr__
    full_name = _UJOIN % (self.__name, name)
  File "C:\Python27\lib\site-packages\pymongo\collection.py", line 228, in __getattr__
    full_name = _UJOIN % (self.__name, name)
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by mmckerns** [comment] 2017-01-30 16:07
Sorry this slipped through the cracks somehow.  Is it still an issue?  If so, let me know.

I've tried the code above, and I don't get the same errors as you.  I'm using more recent versions of the packages, however.

If I use `ThreadPool(1)`, the code succeeds.

If I use `ProcessPool(1)`, the code fails with:
```
Traceback (most recent call last):
  File "test_pymongo.py", line 19, in <module>
    result = ProcessPool(1).map(r.compute, range(2))
  File "/Users/mmckerns/lib/python2.7/site-packages/pathos-0.2.1.dev0-py2.7.egg/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/Users/mmckerns/lib/python2.7/site-packages/multiprocess-0.70.5.dev0-py2.7-macosx-10.12-x86_64.egg/multiprocess/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/mmckerns/lib/python2.7/site-packages/multiprocess-0.70.5.dev0-py2.7-macosx-10.12-x86_64.egg/multiprocess/pool.py", line 567, in get
    raise self._value
pickle.PicklingError: Can't pickle 'poll' object: <select.poll object at 0x108c3c330>
```

And checking directly from `dill`:
```
>>> import select
>>> import dill
>>> dill.copy(select.poll())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 209, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 259, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 252, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 313, in save
    (t.__name__, obj))
pickle.PicklingError: Can't pickle 'poll' object: <select.poll object at 0x10a9efa20>
```

So your code won't work with a `ProcessPool` because a `select.poll` object fails to serialize.  I'll open an issue with `dill`.   Is there any way you can think to work around having the `poll` object serialized?  Sometimes slight modifications to the code can trigger an entirely different serialization path.

**Comment by Alonreznik** [comment] 2017-03-27 08:15
Hello There.
Any kind of solution for that issue? Any workaround?

Thanks!

**Comment by oxydron** [comment] 2017-04-04 20:27
Same problem, trying to use a method from a model object from Keras (tensorflow).
A keras model object has a *predict* method, and using your p.map(model.predict, stuff), I've got this maximum recursion depth problem.

**Comment by mmckerns** [comment] 2017-04-05 03:49
@Alonreznik, @oxydron: Are you seeing the same `PicklingError` as above, or some other error?  If the issue is in pickling of the object, it is possible to rewrite some objects to avoid pickling issues.  Can either of you, or both, post your test codes and tracebacks, if the errors you see are different than what I have posted above?

**Comment by oxydron** [comment] 2017-04-05 14:13
@mmckerns Nope, `TypeError: 'NoneType' object is not callable`

Emphasis on **temp = p.map(vgg.predict, temp)**

Start of the traceback:

```python
Traceback (most recent call last):
  File "vgg16-extract.py", line 33, in <module>
    temp = p.map(vgg.predict, temp)
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/pathos/multiprocessing.py", line 136, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/multiprocess/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/multiprocess/pool.py", line 608, in get
    raise self._value
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/multiprocess/pool.py", line 385, in _handle_tasks
    put(task)
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/multiprocess/reduction.py", line 53, in dumps

...
```
Didn't post full traceback, because is just repetitions, and in the end I got this:

```python
...

  File "/home/bh/anaconda3/envs/keras/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/pickle.py", line 774, in save_list
    self._batch_appends(obj)
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/pickle.py", line 798, in _batch_appends
    save(x)
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/pickle.py", line 473, in save
    f = self.dispatch.get(t)
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/dill/dill.py", line 376, in get
    return self[key]
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fe1da174eb8>>
Traceback (most recent call last):
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 178, in __del__
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 174, in close
TypeError: 'NoneType' object is not callable
```
End of the traceback.

**Comment by Alonreznik** [comment] 2017-04-06 12:20
I get the same Pickling error

**Comment by mmckerns** [comment] 2017-07-12 21:17
@maxbitcoin: is this still an issue for you?

@Alonreznik and @oxydron: if you are getting a different pickling error, and the code is not the same test code... then it's a different issue.  in that case, please open a new ticket.  If not, we can continue here.  Either way, I can't do much to help you with just a traceback.  I need a minimal code example, as @maxbitcoin provided.  If the code is the same, but you are getting a different error, please clarify that for me.

**Comment by sohaibfarooqi** [comment] 2017-10-25 03:54
I am getting same pickling error too:

    _pickle.PicklingError: Can't pickle <class 'select.poll'>: it's not the same object as select.poll

**Comment by mmckerns** [comment] 2019-05-03 02:54
I haven't seen a response to my questions in a long while, so I'm closing this issue as a duplicate.  The issue that @maxbitcoin reported has been opened as a `dill` issue: https://github.com/uqfoundation/dill/issues/207, and will be handled there.  When the serialization issue is resolved (inability to serialize a `poll` object), it will resolve the issue reported here.  Feel free to reopen if there are further comments.

**Closed by mmckerns** 2019-05-03 02:54 UTC
Labels: duplicate
