### ISSUE TITLE
amap usage leads to result printout/loss on get() call

### ISSUE THREAD

**Issue by jaromrax** [uqfoundation/pathos#101] opened 2017-03-03 18:07 UTC
I like amap function and I need it to return large pandas dataframes.
However, I found that when there is a print inside the function for amap,
it will printout also the retrurning dataframe. Which is critical when I return large data.

```
#!/usr/bin/env python3
#
from pathos.parallel import stats
from pathos.parallel import ParallelPool as Pool
import time

pool = Pool()

def host(id ):
    print("my info message")
    return 'jedna,dva,tri'
pool.ncpus = 1  # when nodes replaced by 1
totalchunks=1
res5 = pool.amap( host, range(totalchunks)  )
while not res5.ready():
         time.sleep(1)
         print(stats()  )
pool.close()
pool.join()
print( "=========Printout:")
aaa=res5.get()
csvheader="chunk,host,result\n"
csv=csvheader+"\n".join(res5.get()) 
print( '\n==REAL PRINT==\n',csv)
```

and the result is 
```

=========Printout:
my info message
 ('jedna,dva,tri',) 
==REAL PRINT==
 chunk,host,result
jedna,dva,tri

```
See ('jedna,dva,tri') part.
I use Python 3.5.2 |Anaconda custom (64-bit)

Thanks
Jaromir
 
I realized - when there is a print() inside the function called by amap(),
**only the last result is retrieved** from res5.get()

**Comment by mmckerns** [comment] 2017-03-03 21:18
@jaromrax: I can reproduce your result from your code, however I unfortunately don't understand your question or what you are reporting.  Can you clarify what the issue is?  Is it that the `print` is not printing to `stdout`?  I think all of the pools in `pathos.pools` have similar behavior.

**Comment by mmckerns** [comment] 2017-07-12 21:40
@jaromrax: I'm closing this... because what you are seeing is expected behavior, as I understand it.  Basically, you are spawning different processes, so you shouldn't really see the `print` from these different processes unless they are all piped to the same `stdout`.  This is what I'd expect, and that is why the `ThreadPool` behavior is different.  If you do want to see the prints from each, you'll have to either return what you want printed, or somehow hook up the `stdout` from each process to the originating process.  Please reopen if I'm misinterpreting what you are asking.

**Closed by mmckerns** 2017-07-12 21:40 UTC
Labels: voided
