### ISSUE TITLE
Pathos using pickle because multiprocess fails to compile

### ISSUE THREAD

**Issue by striveLogic** [uqfoundation/pathos#134] opened 2018-04-05 14:46 UTC
@mmckerns I installed using: pip install pathos
No luck. It keeps giving following error:

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    me.start_process()
  File "test.py", line 12, in start_process
    d1 = r1.get()
  File "/usr/lib/python2.7/site-packages/multiprocess-0.70.6.dev0-py2.7.egg/multiprocess/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed

Source Code:
```python
import requests as req
from pathos.multiprocessing import Pool
from multiprocessing import cpu_count

class MigrationEngine():

    def start_process(self):
        pool = Pool(processes=2 if cpu_count() < 2 else cpu_count())
        r1 = pool.apply_async(
            self.testApi, ('http://google.com',))
        d1 = r1.get()
        print d1
        pool.close()
        pool.join()

    def testApi(self, q):
        r = req.get(q)
        print r.status_code
        cont = r.content
        return cont

if __name__ == '__main__':
    me = MigrationEngine()
    me.start_process()
```
It works on my Mac, fails on AWS cloud instance

**Comment by mmckerns** [comment] 2018-04-06 04:02
@striveLogic: the error that you are seeing typically is what you'd see if you are missing a C compiler.  You are saying that you not seeing failure on your computer, but are seeing failure on the AWS cloud?  What's the environment look like on the AWS instance?

Can you please edit your code snippet above?   Also give me the information on what you have installed? I can see the version of `multiprocess` and python from your traceback, but not `pathos` etc.

**Comment by striveLogic** [comment] 2018-04-06 18:25
@mmckerns Sorry, I did not get you on the editting part, what would you like me to edit in my code snippet?

Pathos and Dill are installed, i am able to import libraries
From AWS Instance:
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathos
>>> pathos.__file__
'/usr/lib/python2.7/site-packages/pathos-0.2.2.dev0-py2.7.egg/pathos/__init__.pyc'
>>> pathos.__version__
'0.2.2.dev0'
>>> import dill
>>> dill.__file__
'/usr/lib/python2.7/site-packages/dill/__init__.pyc'
>>> dill.__version__
'0.2.7.1'

**Comment by mmckerns** [comment] 2018-04-09 12:12
@striveLogic: What you've done above and provided is fine.  I tested your code, and it works for me locally.  I'll have to figure out how to test it on AWS, or find out what might be missing from the AWS environment.  Any suggestions?

Can you check what is the C compiler on the AWS instance?  The error you are seeing is indicative of `multiprocess` not being installed correctly, due to being built without a C compiler.

**Comment by striveLogic** [comment] 2018-04-09 14:15
@mmckerns 
I ran the command: yum group install "Development Tools"
and on yum list installed it gives me:
gcc.x86_64                              4.8.5-16.el7_4.2               @updates 
gcc-c++.x86_64                          4.8.5-16.el7_4.2               @updates 
gcc-gfortran.x86_64                     4.8.5-16.el7_4.2               @updates 
libgcc.x86_64                           4.8.5-16.el7_4.2               @updates 

gcc --version gives me:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

Do we need a specific compiler for multiprocess?

**Comment by mmckerns** [comment] 2018-04-10 02:16
No that should work.

**Comment by striveLogic** [comment] 2018-04-16 21:02
@mmckerns I have not heard from you. Is there something that is needed from my end?

**Comment by mmckerns** [comment] 2018-04-17 19:15
I've not had time to investigate further just yet.   In summary, your test code works locally on every platform I test on.  However, you've installed on AWS, and from the instal information you are providing, it looks like it should also work there.  It apparently something doesn't work on AWS.  So, either I have to get an AWS account and test it on AWS, or we dig around otherwise.

**Comment by mmckerns** [comment] 2018-04-17 19:17
What happens on AWS when you do this:

`>>> import _multiprocess`

**Comment by striveLogic** [comment] 2018-04-17 19:33
@mmckerns 
```
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _multiprocess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _multiprocess
```

Gives me above. I am now trying on a new Centos 7 installation, same error as before

**Comment by mmckerns** [comment] 2018-04-17 19:57
Ok, so, at least we confirmed the cause of the error.  Now, the question is why it fails.  Note that I didn't test against python 2.7.5 since I didn't notice that your python was that old until just now.  Let me know if the python upgrade works.

**Comment by striveLogic** [comment] 2018-05-10 15:49
@mmckerns 
Update: Centos/Amazon Linux, as earlier stated by you, may have compile issues. I ran Ubuntu image in Docker and everything works as expected.

You may close this ticket. Thanks a for your help. I really appreciate it.

**Comment by mmckerns** [comment] 2018-05-10 21:29
Ok, closing.

**Closed by mmckerns** 2018-05-10 21:29 UTC
Labels: compatibility

**Comment by rustylampshade** [comment] 2018-08-13 20:01
No action needed, but I just wanted to chime in since I'd been seeing very similar behavior to @striveLogic . Despite seemingly having a C compiler installed I wasn't getting the _multiprocess module, and then would get PickleErrors when I ran my program. The problem turned out to be lacking the python-devel package, so that when multiprocess was building it could not find Python.h. 

My env: 
```
Python 2.7.5 (default, May 31 2018, 09:41:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathos
>>> pathos.__version__
'0.2.2.1'
>>> import multiprocess
>>> multiprocess.__version__
'0.70.6.1'

gcc.x86_64                                     4.8.5-28.el7_5.1         @server 
gcc-c++.x86_64                                 4.8.5-28.el7_5.1         @server 
gcc-gfortran.x86_64                            4.8.5-28.el7_5.1         @server 
libgcc.i686                                    4.8.5-28.el7_5.1         @server 
libgcc.x86_64                                  4.8.5-28.el7_5.1         @server
```
When building multiprocess from source as @mmckerns suggested here https://github.com/uqfoundation/pathos/issues/121#issuecomment-335648576 gave me this error: 

```
In file included from py2.7/Modules/_multiprocess/multiprocess.c:9:0:
py2.7/Modules/_multiprocess/multiprocess.h:12:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.


-----------------------------------------------------------------------
WARNING: The C extensions could not be compiled
-----------------------------------------------------------------------

Maybe you do not have a C compiler installed on this system?
The reason was:
  File "setup.py", line 415, in <module>
    msg = BUILD_WARNING % '\n'.join(traceback.format_stack())


This is just a warning as most of the functionality will work even
without the updated C extension.  It will simply fallback to the
built-in _multiprocessing module.  Most notably you will not be able to use
FORCE_EXECV on POSIX systems.  If this is a problem for you then please
install a C compiler or fix the error(s) above.
```

A simple `yum install python-devel` fixed my issue. Simple in retrospect. Thankfully the clear ticket discussions here helped immensely in getting past it.

**Comment by mmckerns** [comment] 2018-09-17 00:12
@rustylampshade: Thanks for the additional comments.  I think if I built a wheels for `multiprocess`, that would remove the need for people to install a compiler (on windows) or the headers from python-devel (otherwise). NOTE: https://github.com/uqfoundation/multiprocess/issues/8
