### ISSUE TITLE
pool can't be terminated correctly

### ISSUE THREAD

**Issue by quantwizard** [uqfoundation/pathos#82] opened 2016-04-06 03:45 UTC
I am using the Pool from pathos.multiprocessing. However the pool can't be terminated correctly.
I attached my code snippet in the file.

[problem.txt](https://github.com/uqfoundation/pathos/files/205755/problem.txt)

all methods are in class Receiver. the handler will be called when receiver get a job, then it will create RtmpClient objects and use Pool to launch processes to run the client.run(). The problems is when the receiver got the 4th job, it will always report like below:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/multiprocess/util.py", line 321, in _exit_function
    p._popen.terminate()
  File "/usr/local/lib/python2.7/site-packages/multiprocess/forking.py", line 174, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 3] No such process
So how do I fix it?

**Comment by mmckerns** [comment] 2016-04-13 10:11
Looking at your code, I see it's not complete, and it's not minimal -- so I will try to answer without being able to execute your code.  

I think, in the abstract, it might be related to this python bug.
https://bugs.python.org/issue17131
https://bugs.python.org/issue6973

What is your python version and OS?

**Comment by mmckerns** [comment] 2016-06-02 17:39
closing due to staleness from reporter -- and my not being able to reproduce the bug.

**Closed by mmckerns** 2016-06-02 17:39 UTC
Labels: voided
