### ISSUE TITLE
Pickling errors with simple examples

### ISSUE THREAD

**Issue by vsimonis** [uqfoundation/pathos#67] opened 2015-07-09 19:55 UTC
I am getting pickling errors as in #55 on very simple code after installing pathos from here using `pip install git+https://github.com/uqfoundation/pathos.git`

After going through stack exchange I've tried some of the posted examples of using `pathos.multiprocessing` and receive the same `cPickle.PicklingError`. I'm running Windows 8.1 and a 64-bit install of python 2.7.8. Any help is greatly appreciated!

For example, from http://stackoverflow.com/questions/19984152/what-can-multiprocessing-and-dill-do-together/19985580#19985580

```
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> from pathos.multiprocessing import ProcessingPool
>>> pool = ProcessingPool( nodes = 4 )
>>> result = pool.map( lambda x: x**2, range(10))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pathos\multiprocessing.py", line 131, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 558, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

or this one http://stackoverflow.com/questions/3288595/multiprocessing-using-pool-map-on-a-function-defined-in-a-class/21345308#21345308
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\SysWOW64>python
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathos.multiprocessing import ProcessingPool as Pool
>>> p = Pool(4)
>>> def add( x,y):
...     return x+y
...
>>> x = [0,1,2,3]
>>> y = [4,5,6,7]
>>> p.map( add, x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pathos\multiprocessing.py", line 131, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 558, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

**Comment by mmckerns** [comment] 2015-07-11 01:04
This looks like it's an issue with `multiprocessing` on Windows.  So question #1, did you install `multiprocess` (it's a fork of `multiprocessing`)?  You are seeing `cPickle` errors, which shouldn't happen if `pathos` is finding `dill` and `multiprocess`.  Can you tell me a little about your install of these dependencies?

Second item to note is that Windows works differently than non-windows systems.  Much of the time, for the `ProcessPool`, Windows requires `from pathos.helpers import freeze_support`, then `freeze_support()`.  It's unnecessary for non-windows systems.  Windows often requires `freeze_support` to be provided in `__main__`.

**Comment by mmckerns** [comment] 2015-07-16 14:41
I can't reproduce what you are seeing.  Those examples work for me, as typed above (i.e. without `freeze_support`).  I'm guessing you are missing `multiprocess`, and that's why you are seeing `cPickle`.  I'm closing this, but I'll reopen it if I hear back from you with an update.  I could always be wrong.

**Closed by mmckerns** 2015-07-16 14:41 UTC
Labels: voided

**Comment by vsimonis** [comment] 2015-07-16 15:04
Thanks for looking into this! I got it working by going to a 32-bit version of python and reinstalling all my libraries.

**Comment by mmckerns** [comment] 2015-07-16 17:42
Ok, cool.  Thanks for the post.

**Comment by abrazhe** [comment] 2015-09-15 13:14
I can reproduce it on a 64-bit windows Anaconda installation (`dill` and `pathos` being installed from git):

```
import dill

from pathos.multiprocessing import ProcessingPool

pool = ProcessingPool(ncpus=4)

def _f (a): return a**2

pool.map(_f, range(19))
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-5-14a449cbe281> in <module>()
----> 1 pool.map(_f, range(19))

C:\Anaconda\lib\site-packages\pathos\multiprocessing.pyc in map(self, f, *args, **kwds)
    129         AbstractWorkerPool._AbstractWorkerPool__map(self, f, *args, **kwds)
    130         _pool = self._serve()
--> 131         return _pool.map(star(f), zip(*args)) # chunksize
    132     map.__doc__ = AbstractWorkerPool.map.__doc__
    133     def imap(self, f, *args, **kwds):

C:\Anaconda\lib\multiprocessing\pool.pyc in map(self, func, iterable, chunksize)
    249         '''
    250         assert self._state == RUN
--> 251         return self.map_async(func, iterable, chunksize).get()
    252 
    253     def imap(self, func, iterable, chunksize=1):

C:\Anaconda\lib\multiprocessing\pool.pyc in get(self, timeout)
    565             return self._value
    566         else:
--> 567             raise self._value
    568 
    569     def _set(self, i, obj):

PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

dill.__version__
Out[6]: '0.2.5.dev0'

import pathos

pathos.__version__
Out[8]: '0.2a1.dev0'
```

**Comment by mmckerns** [comment] 2015-09-15 13:28
@abrazhe: This is not reproducing the same error.  @vsimonis was getting a `cPickle.PicklingError`, which stems from `pathos` getting hooked up to the wrong version of `multiprocessing` and/or `pickle`, so that the `dill` serializer was not used.  Your error the typical error that is thrown indicating you are on Windows and have not used `freeze_support`.

**Comment by abrazhe** [comment] 2015-09-15 13:43
@mmckerns it doesn't seem to work with `freeze_support` either, or am I doing it wrong?

````
from pathos.helpers import freeze_support

freeze_support()

from pathos.multiprocessing import ProcessingPool

pool = ProcessingPool(nodes=4)

pool.map(lambda x: x**2, range(19))
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-5-71461c05efb7> in <module>()
----> 1 pool.map(lambda x: x**2, range(19))

C:\Anaconda\lib\site-packages\pathos\multiprocessing.pyc in map(self, f, *args, **kwds)
    129         AbstractWorkerPool._AbstractWorkerPool__map(self, f, *args, **kwds)
    130         _pool = self._serve()
--> 131         return _pool.map(star(f), zip(*args)) # chunksize
    132     map.__doc__ = AbstractWorkerPool.map.__doc__
    133     def imap(self, f, *args, **kwds):

C:\Anaconda\lib\multiprocessing\pool.pyc in map(self, func, iterable, chunksize)
    249         '''
    250         assert self._state == RUN
--> 251         return self.map_async(func, iterable, chunksize).get()
    252 
    253     def imap(self, func, iterable, chunksize=1):

C:\Anaconda\lib\multiprocessing\pool.pyc in get(self, timeout)
    565             return self._value
    566         else:
--> 567             raise self._value
    568 
    569     def _set(self, i, obj):

PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
````

**Comment by abrazhe** [comment] 2015-09-15 13:53
Actually, it *may* be the same problem, as when I run `python nested.py`  in the examples directory I get the `cPickle.PicklingError`

**Comment by mmckerns** [comment] 2015-09-15 14:06
If you are getting a `cPickle.PicklingError`, then yes.  That's a configuration problem.  One of the issues can be if you had a prior install of `pathos` before the `multiprocess` package was split out into it's own package.  I'm not sure what the issue is, as I have not been able to reproduce the `cPickle` problem from a fresh install.  More detail here might be good.

With regard to when you use `freeze_support` on windows, it also needs to be in a `if __name__ == '__main__'` block, because windows doesn't have a proper fork.  Try that. and if it fails in a `__main__` block, then it's an issue.

**Comment by abrazhe** [comment] 2015-09-15 14:30
I just installed Anaconda (windows), and then I ran
`pip install -U http://github.com/uqfoundation/pathos/archive/master.zip`
this automatically installed `dill` and `multiprocess` packages for me.

adding `freeze_support()` to my script led to another problem: it would repeatedly raise `ImportError: no module named  funcut`, where `funcut` is the name of my script, but the actual `pool.map` calls are in another module, that is getting imported into `funcut`, which I run. The same application works fine on ubuntu 15.04 (with anaconda python installation). 

But as I mentioned, the problem is already with the examples that come with `pathos`, and I get different error messages when I run them with `python file.py` or `ipython file.py`.
Hope this will help to find out what and where the problem is. May it actually be `anaconda` problem or the way I install the `pathos` package?

**Comment by abrazhe** [comment] 2015-09-15 20:07
I just reproduced the error on another machine (Windows 8.1 64 bit).
I installed anaconda (just for the user). Then I used `git` to clone multiprocess, dill, and pathos (all from master branches). Then I did `pip install .` in each directory in this order: multiprocess, dill, pathos.

Then, when I go to `pathos/examples` and run `python nested.py` I get this:
```
C:\Users\---\src\pathos\examples>python nested.py
Traceback (most recent call last):
  File "nested.py", line 23, in <module>
    print amap(f, [h(x),h(x),h(x),h(x),h(x)], y).get()
  File "C:\Users\---\Anaconda\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

C:\Users\Alexey\src\pathos\examples>ipython nested.py
```

What did I get wrong and how this can be fixed?

**Comment by mmckerns** [comment] 2015-09-15 20:24
Hmm.. ok, that's weird.  Your instructions are such that I should be able to see if I can reproduce what you see.

Can you also distill your `funcut` example to something minimal, and then post it here as an example, showing the error?  That would help me diagnose what's going on.

**Comment by abrazhe** [comment] 2015-09-15 20:34
`funcut` is a biggish script that uses `traitsui` and all sorts of stuff. At the moment I am figuring out how to at least run the examples without errors.

So far I figured out that I actually can't `import mutiprocess` although it has been happily installed by pip. So the the issue with `pathos` is that it is silent when it can't load `multiprocess` in `pathos/helpers/__init__.py` I suppose it could issue a warning if it falls back to `multiprocessing` from python. 

Now, the issue I have with multiprocess  is this:

```
>>> import multiprocess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\---\Anaconda\lib\site-packages\multiprocess\__init__.py", line 84, in <module>
    import _multiprocess as _multiprocessing
ImportError: No module named _multiprocess
```
Is this something trivial or should I open an issue in `multiprocess` repo?

**Comment by mmckerns** [comment] 2015-09-15 21:31
I see. Yes, `pathos` falls back to `multiprocessing` if `multiprocess` is not found.  It should also fall back to `processing` (for `2.x`) if that is found and `multiprocess` is not found.  The issue you are seeing is because the `_multiprocess` submodule did not install.  Likely, the small bit of C code in the `2.x` version of `multiprocess` did not compile, and you are falling back to the  `_multiprocess` found in standard python -- and thus doesn't use `dill`.  Hence, the pickling error.

The issue, and the reason I couldn't reproduce it, is probably because you don't have a C compiler.
The compiler is not building/linking the `_multiprocess` module (which for `2.x` includes some C).

**Comment by abrazhe** [comment] 2015-09-15 21:48
Thank you very much for your help!
After installing mvc for python (http://aka.ms/vcpython27) and required (i think) redistributable package from http://www.microsoft.com/en-us/download/confirmation.aspx?id=2092 and rebuilding multiprocess the examples work fine.

**Comment by mmckerns** [comment] 2015-09-15 21:48
This is actually an issue, due to attempting to build without a C compiler. 
However, it's a `multiprocess` issue, not a `pathos` issue.
See: https://github.com/uqfoundation/multiprocess/issues/8

**Comment by wolfiex** [comment] 2019-06-05 13:50
Reproducing on Linux: 

```
import dill
from pathos.multiprocessing import ProcessingPool    
pool = ProcessingPool(nodes=4)
result = pool.map(lambda x: x**2, range(10))
```

```
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

**Comment by Yash0270** [comment] 2019-06-10 20:35
Reproducing in MacOS:
```import dill 
from pathos.multiprocessing import ProcessingPool as Pool
import pdb

class A(object):
  def __init__(self, njobs=1000):
    self.map = Pool().map
    self.njobs = njobs
    self.start()
  def start(self):
    self.result = self.map(self.RunProcess, range(self.njobs))
    return self.result
  def RunProcess(self, i):
    return i*i

myA = A()
pdb.set_trace()
```

  File "/anaconda2/lib/python2.7/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/anaconda2/lib/python2.7/site-packages/multiprocess/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/anaconda2/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

**Comment by mmckerns** [comment] 2019-06-18 05:06
@wolfiex: I can't reproduce your error, and I don't have enough information about your version of python and dill, multiprocess, pathos, etc.  The full traceback is at least a bit helpful for that.  `dill` can absolutely pickle a `lambda`, and that's the only thing being serialized here, so again, I expect this is an install/config issue of some sort for `multiprocess`.

@Yash0270: I also can't reproduce your error.  However, the fact the traceback is reporting a `cPickle` error tells me it's not using `dill`, and thus `multiprocess` had some install/config issue.
