### ISSUE TITLE
ProcessingPool.map() hangs on KeyboardInterrupt

### ISSUE THREAD

**Issue by erp12** [uqfoundation/pathos#114] opened 2017-07-16 15:58 UTC
When I send a `KeyboardInterrupt` while a `ProcessingPool.map()` is being called, a large scramble of stack trace is printed and my terminal hangs indefinitely. I can see all processes are still present int the activity monitor, and I have to kill the master python process.

I am on OSX using `pathos` 0.2.1 and I can recreate this behavior consistently in python 2.7 and python 3.5.

Below I have listed the class method where I initialize the pool, and the class method where I call `map()`.

```py
from pathos.multiprocessing import ProcessingPool as Pool

class Foo:

    ...

    def init_executor(self):
        if self.n_jobs == 1:
            return

        if self.n_jobs == -1:
            self.pool = Pool()
        else:
            self.pool = Pool(self.n_jobs)

    def _evaluate_population(self, X, y):
        def f(i):
            if not hasattr(i, 'error_vector'):
                return self._evaluate_individual(i, X, y)
            return i

        if hasattr(self, 'pool'):
            self.population[:] = self.pool.map(f, self.population)
        else:
            for i in self.population:
                f(i)
```
Am I doing something incorrectly? I have seen [an issue](http://bugs.python.org/issue8296) that indicates this is an issue in python's multiprocessing library as well, but that was years ago. If this is a known issue, is there a workaround? Thanks in advance.

**Comment by mmckerns** [comment] 2017-07-18 17:36
I believe it is unresolved (i.e I didn't test it, but judging from the link you posted) in `multiprocessing`, and thus is also unresolved in `multiprocess`.

**Comment by mmckerns** [comment] 2017-07-18 17:58
You can see that there's a test script here that succeeds for both `multiprocess` and `multiprocessing`: http://bugs.python.org/file16784/test_map_keyboard_interrput.py.  The links following the link you referenced seem to indicate that the issue is closed, but not resolved in all cases.  So, I'm guessing that the bug persists.  Can you share some (complete) minimal test code that reproduces the bug?  Apparently, the workaround is to use `map_async` and `get` with a timeout.

**Comment by mmckerns** [comment] 2017-11-06 05:16
Anyone who's observed the failure described here, can you post your code, so I have some code that fails in the manner described?

**Comment by HBadertscher** [comment] 2018-04-18 10:39
Hi @mmckerns 

I have the same issue with `ProcessingPool.map()` from `pathos.multiprocessing`. Here is a minimal example of the issue:

```
from pathos.multiprocessing import ProcessingPool as Pool
import time

def worker(k):
    time.sleep(10)
    return k

p = Pool(4)
p.map(worker, range(100))
```
When pressing `<Ctrl>+C` while this is running, I get a long traceback, and multiple `KeyboardInterrupt` are shown in the console, but the terminal hangs without any possibility to close. Pressing `<Ctrl>+C` again leads to more output, but the program is not closed.

It seems to me that the worker-processes are closed upon a `KeyboardInterrupt`, but new processes are being spawned.

I am using Python 2.7.12 and Pathos 0.2.1.

**Comment by tcourdy** [comment] 2019-05-07 20:01
Was curious if there is a fix for this on the roadmap?

**Comment by tcourdy** [comment] 2019-05-07 21:34
For what its worth I ended up doing what was suggested here: https://github.com/uqfoundation/pathos/issues/151#issuecomment-422242145 and used an initializer function that did this:

```
def init_worker():
    signal.signal(signal.SIGINT, signal.SIG_IGN)
```

**Comment by ddelange** [comment] 2022-09-30 03:58
By [explicitly handling](https://github.com/ddelange/mapply/blob/0.1.16/src/mapply/parallel.py#L108) the KeyboardInterrupt (not a subclass of Exception), I can repeatedly recreate pools and kill them early, within the same Python session.

**Comment by mmckerns** [comment] 2022-10-23 03:20
I'm going to close this, as the question was about 2.7 which is no longer supported.  With regard to 3.x, the KeyboardInterrupt should be caught.
```
Python 3.7.15 (default, Oct 12 2022, 04:11:53) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathos.multiprocessing import ProcessingPool as Pool
>>> import time
>>> 
>>> def worker(k):
...     time.sleep(10)
...     return k
... 
>>> p = Pool(4)
>>> p.map(worker, range(100))
^CProcess ForkPoolWorker-1:
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/mmckerns/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mmckerns/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mmckerns/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/mmckerns/lib/python3.7/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "<stdin>", line 2, in worker
KeyboardInterrupt

>>> 
```

**Closed by mmckerns** 2022-10-23 03:20 UTC
Labels: question
