### ISSUE TITLE
ModuleNotFoundError: No module named 'pathos.multiprocessing'

### ISSUE THREAD

**Issue by rkatriel-mdsol** [uqfoundation/pathos#149] opened 2018-08-30 16:35 UTC
Hi,

I installed pathos (using pip3.6) on an Ubuntu Linux instance in AWS but am getting the following error when trying to run a Python3.6 program that works fine on another (virtually identical) Linux instance:

ModuleNotFoundError: No module named 'pathos.multiprocessing'

I found a few references to this issue by googling the error message but no real solution. Pathos appears to be installed correctly (see the trace below).

 Looking forward to your suggestions.

Thanks,
Ron

$ sudo -H pip3.6 install pathos
Requirement already satisfied: pathos in /usr/local/lib/python3.6/dist-packages (0.2.2.1)
Requirement already satisfied: pox>=0.2.4 in /usr/local/lib/python3.6/dist-packages (from pathos) (0.2.4)
Requirement already satisfied: ppft>=1.6.4.8 in /usr/local/lib/python3.6/dist-packages (from pathos) (1.6.4.8)
Requirement already satisfied: dill>=0.2.8.2 in /usr/local/lib/python3.6/dist-packages (from pathos) (0.2.8.2)
Requirement already satisfied: multiprocess>=0.70.6.1 in /usr/local/lib/python3.6/dist-packages (from pathos) (0.70.6.1)
Requirement already satisfied: six>=1.7.3 in /usr/lib/python3/dist-packages (from ppft>=1.6.4.8->pathos) (1.10.0)

**Comment by rkatriel-mdsol** [comment] 2018-08-30 20:19
Update: This issue is specific to the python version installed using Linuxbrew. I installed anaconda and the issue went away. In case it matters, the former uses GCC 5.4.0 while the latter was build with [GCC 7.2.0].

**Comment by mmckerns** [comment] 2018-08-31 13:53
First off, is this still an issue for you?  If not, you can close it.
Otherwise, I'll need more information than the above.  It would appear that `pathos` is installed. So the next question would be could you `import pathos`?  And if so, what do you see when you do `dir(pathos)`?

**Comment by rkatriel-mdsol** [comment] 2018-08-31 15:38
Hi Mike. This is not an issue anymore. Installing the Anaconda version of
python solved the issue.

Regarding your debugging request, below is the trace from the version of
python that does not work. Immediately below it is the trace from the
Anaconda version that works. Comparing both, it looks like the modules were
not loaded into the default version of python.

Thanks,
Ron


$ /usr/bin/python3.6

Python 3.6.6 (*default*, Jun 28 2018, 04:42:43)

[GCC 5.4.0 20160609] on linux

Type "help", "copyright", "credits" or "license" for more information.

>>> import pathos

>>> dir(pathos)

['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

>>>


$ python3.6

Python 3.6.3 |*Anaconda*, Inc.| (default, Oct 13 2017, 12:02:49)

[GCC 7.2.0] on linux

Type "help", "copyright", "credits" or "license" for more information.

>>> import pathos

>>> dir(pathos)

['SCP_Launcher', 'SSH_Launcher', 'SSH_Tunnel', '__author__',
'__builtins__', '__cached__', '__doc__', '__file__', '__license__',
'__loader__', '__name__', '__package__', '__path__', '__spec__',
'__version__', 'abstract_launcher', 'citation', 'connection', 'core',
'helpers', 'hosts', 'info', 'license', 'logger', 'multiprocessing',
'parallel', 'pools', 'pp', 'python', 'secure', 'selector', 'serial',
'server', 'threading', 'util']

>>>

On August 31, 2018 at 9:53:19 AM, Mike McKerns (notifications@github.com)
wrote:

First off, is this still an issue for you? If not, you can close it.
Otherwise, I'll need more information than the above. It would appear that
pathos is installed. So the next question would be could you import pathos?
And if so, what do you see when you do dir(pathos)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/uqfoundation/pathos/issues/149#issuecomment-417671193>,
or mute the thread

**Comment by mmckerns** [comment] 2018-08-31 23:39
@rkatriel-mdsol: That's weird... I don't think I've seen something like that, where the modules are missing.  Maybe it's a bad build... I don't know why that would happen.  However, since you have a resolution, I'm going to close this.  I'll assume if someone else has this same issue, they will comment here.

**Closed by mmckerns** 2018-08-31 23:39 UTC
Labels: voided

**Comment by Redysz** [comment] 2019-07-20 20:23
I have the same problem. Version downloaded by pip: 0.2.4.
Code:
`from pathos.multiprocessing import ProcessPool as Pool
import pathos

print(dir(pathos))
p = Pool(8)`

gives me:
`['SCP_Launcher', 'SSH_Launcher', 'SSH_Tunnel', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__license__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'abstract_launcher', 'citation', 'connection', 'core', 'helpers', 'hosts', 'info', 'license', 'logger', 'multiprocessing', 'parallel', 'pools', 'pp', 'python', 'secure', 'selector', 'serial', 'server', 'threading', 'util']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'`

There is one difference: **multiprocess** and **multiprocessing**

**Comment by mmckerns** [comment] 2019-08-31 17:27
@Redysz:  `ModuleNotFoundError: No module named 'multiprocess`... looks like a spelling error???

**Comment by carcigenicate** [comment] 2019-09-27 20:01
> @mmckerns
> I have the same problem. Version downloaded by pip: 0.2.4.
> Code:
> 
> ```
> from pathos.multiprocessing import ProcessPool as Pool
> import pathos
> 
> print(dir(pathos))
> p = Pool(8)
> ```
> 
> gives me:
> 
> ```
> ['SCP_Launcher', 'SSH_Launcher', 'SSH_Tunnel', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__license__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'abstract_launcher', 'citation', 'connection', 'core', 'helpers', 'hosts', 'info', 'license', 'logger', 'multiprocessing', 'parallel', 'pools', 'pp', 'python', 'secure', 'selector', 'serial', 'server', 'threading', 'util']
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocess'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocess'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocess'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocess'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocess'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocess'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocess'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'multiprocess'
> ```
> 
> There is one difference: **multiprocess** and **multiprocessing**.
> Packages which I have installed (by pip):
> `dill`, `multiprocess`, `pathos`, `pip`, `pox`, `ppft`, `setuptools`, `six`

I had this problem. It seems to be a PATH issue.

I had run `pip install pathos` inside the PyCharm terminal, and got this error. I was able to fix it by running `pip install pathos` in the windows terminal. Not sure exactly what the problem is, but at least it's working now.
