### ISSUE TITLE
Lets add "__exit__" for ProcessPool

### ISSUE THREAD

**Issue by levkovalenko** [uqfoundation/pathos#208] opened 2021-03-18 11:20 UTC
Hi guys, i use your lib in my project and noticed that ProcessPool doesn't close after "with" construction. \
So I started research this problem ans found that methods `___enter__` and `__exit__` are empty.
Proof: [\__enter__](https://github.com/uqfoundation/pathos/blob/67c714b4052ebd5b91a21ef55bb1d18fad8727ab/pathos/abstract_launcher.py#L110), [\__exit__](https://github.com/uqfoundation/pathos/blob/67c714b4052ebd5b91a21ef55bb1d18fad8727ab/pathos/abstract_launcher.py#L112)

Moreover I found [\__exit__](https://github.com/uqfoundation/pathos/blob/67c714b4052ebd5b91a21ef55bb1d18fad8727ab/pathos/multiprocessing.py#L112) method in ProcessPool, but it was commented about 8 years ago by @mmckerns.

I believe that its time has come. So can i uncomment it and make pool request with this changes?

**Comment by mmckerns** [comment] 2021-03-19 12:36
I'm not sure why the implementation is as it is.  Hmm.  I'd have to look into it.  Feel free to uncomment it, and make a pull request.  You'll want to add tests to make sure that it behaves as expected.

**Comment by mmckerns** [comment] 2021-06-11 16:21
@levkovalenko: I believe I remember why the exit method was commented out.  It was because pools in pathos persist beyond the close, and can be reopened and restarted.  So, I felt that leaving a context shouldn't shut them down.  I'm taking a look at making changes to this behavior.

**Comment by mmckerns** [comment] 2023-02-01 04:39
closing as duplicate of #8

**Closed by mmckerns** 2023-02-01 04:39 UTC
Labels: question
